{print} = require 'util'
{spawn} = require 'child_process'

build = (callback) ->
  coffee = spawn 'coffee', ['-cj', './derp.js', 'src/Lobby.coffee']
  
task 'build', 'Build lib/ from src/', ->
  build()