// Generated by CoffeeScript 1.3.1

/*
  Lobby Class
  Used for player pairing
  Logic Involved..
   - There should never be more than 2 users in a lobby at a time.
   - Once the lobby reaches 2 active users, they should be paired and passed on to the game. Lobby count should be set to 0.
   - If a user in the lobby disconnects or loses their connection, the counter needs to reflect that.
   - If a user loses a connection during the setup of a game, their partner should be bounced back to the lobby.
  
  Exposed Methods and Values
   - addUser(userSocketId) : Adds a User to the Lobby. Takes 1 arguement, user's connection/socket ID.
   - getCount : Returns the number of waiting users. 
   - getUsers : Returns an Object of waiting users.
*/


(function() {
  var Lobby, app, io, lobby;

  Lobby = (function() {
    var currentWaitingUsers, numberOfWaitingUsers;

    Lobby.name = 'Lobby';

    function Lobby() {}

    numberOfWaitingUsers = 0;

    currentWaitingUsers = [];

    Lobby.prototype.addUser = function(userSocketId) {
      numberOfWaitingUsers += 1;
      currentWaitingUsers.push(userSocketId);
      this.tryToPair;
      return true;
    };

    Lobby.prototype.tryToPair = function() {
      if (weShouldPair) {
        /*
              PAIR LOGIC HERE
        */

        numberOfWaitingUsers = 0;
        currentWaitingUsers = [];
      }
      return true;
    };

    Lobby.prototype.weShouldPair = function() {
      if (numberOfWaitingUsers === 2) {
        return true;
      }
      return false;
    };

    Lobby.prototype.getUsers = function() {
      return currentWaitingUsers;
    };

    Lobby.prototype.getCount = function() {
      return numberOfWaitingUsers;
    };

    return Lobby;

  })();

  app = require('express').createServer();

  io = require('socket.io').listen(app);

  lobby = new Lobby;

  app.listen(80);

  app.get('/', function(req, res) {
    return res.sendfile(__dirname + '/index.html');
  });

  io.sockets.on('connection', function(socket) {
    lobby.addUser(socket.id);
    return socket.emit('news', "connected, your connection id is " + socket.id);
  });

}).call(this);
